[[Minuit2]]
arch = "aarch64"
git-tree-sha1 = "4afa81fd17c8d2616a0895f609579f19a4e4e4b7"
os = "macos"

    [[Minuit2.download]]
    sha256 = "a25d06802a27d80b1d8463d7ba1e94d31ab3753c0c5d3e0a34e281e0b117fb6e"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.aarch64-apple-darwin.tar.gz"
[[Minuit2]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fccb3e6bea96cc702fbb65e07a5bb2e638bdd79a"
libc = "glibc"
os = "linux"

    [[Minuit2.download]]
    sha256 = "93beefaa9595165a4ca156f4eadde5227c32cef2bc8094db0b1783c4b2b19ff6"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.aarch64-linux-gnu-cxx03.tar.gz"
[[Minuit2]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b02d467eed94b7dedd760340242b466dbe64901a"
libc = "glibc"
os = "linux"

    [[Minuit2.download]]
    sha256 = "ed914c614f2a5037624fd60b3075406dda7f8ed3175fae76037d9741ebff4b5b"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.aarch64-linux-gnu-cxx11.tar.gz"
[[Minuit2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5cb3bb9ca665def528923542e70bc1bfe160afe9"
libc = "glibc"
os = "linux"

    [[Minuit2.download]]
    sha256 = "a0d74d8904a3a52c1a4d131584b3073aceb00283dfb8a13f1b2c5914e84180bb"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Minuit2]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d6c8014c647369e714a8dc632c7e3f5608d0054"
libc = "glibc"
os = "linux"

    [[Minuit2.download]]
    sha256 = "a59245142e1095c4a772c4ff492a6e89ff264aec452092cefad9aa80bf0fe258"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Minuit2]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61b68429a54591643a1c4c3dd5b71851b5c2b910"
libc = "glibc"
os = "linux"

    [[Minuit2.download]]
    sha256 = "6735936e6482f8c56a3de025a9c6ace0d683d8b9f638fd1f4c9e96a0991b77f2"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Minuit2]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "adbe92c6d6f45c857f0f32eb0c069de7e91ed96e"
libc = "glibc"
os = "linux"

    [[Minuit2.download]]
    sha256 = "505afe33326051f06b20857597b1238c3d9dcb0a7c685d7a81be84941a1a289b"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Minuit2]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2875668f9cb08f1c8e43404e16a6c6f416314661"
libc = "glibc"
os = "linux"

    [[Minuit2.download]]
    sha256 = "36cd517a73a6a6eac745f07c311e9cea9537aea88b4a3ba3d41a3e242f79ee1f"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.riscv64-linux-gnu-cxx03.tar.gz"
[[Minuit2]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d25672ae68b0c421084bb0cc035a61941218b23"
libc = "glibc"
os = "linux"

    [[Minuit2.download]]
    sha256 = "a8d8a4dce34c5a33bf57b1dd90d23a549c2d8b0d5fbe5c6ee365a477fa436700"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.riscv64-linux-gnu-cxx11.tar.gz"
[[Minuit2]]
arch = "x86_64"
git-tree-sha1 = "ce2caf211b7584d5f77782dd55705c0bd0e5412d"
os = "macos"

    [[Minuit2.download]]
    sha256 = "167e107b91806ee7c90c60dc4c9994cb0e140416ea9ee0ddd8f569cde88ce951"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.x86_64-apple-darwin.tar.gz"
[[Minuit2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0fe6856803960813ebd99697d7856832c022cd5"
libc = "glibc"
os = "linux"

    [[Minuit2.download]]
    sha256 = "d0fa90efce07d2c761f21e6f93c0450bf8d201d56a5221315585368de59177c9"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.x86_64-linux-gnu-cxx03.tar.gz"
[[Minuit2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0938591bd9137ec1bc17c65d0ef6b3bb268ff00f"
libc = "glibc"
os = "linux"

    [[Minuit2.download]]
    sha256 = "4dc1d62ee335413d9a6ff6e052f812f8591277cea6fe02da7888044ebc395887"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.x86_64-linux-gnu-cxx11.tar.gz"
[[Minuit2]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90c91a314d7220846a43a4db155d33277c3cbd35"
os = "windows"

    [[Minuit2.download]]
    sha256 = "ce48132de4fbe6e3f0cd765d156b28eeb671769892538c8ee6f2bd4bb172d9e3"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[Minuit2]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8f5988fe60c9c1646b7ecce875f57ad51dcb6a42"
os = "windows"

    [[Minuit2.download]]
    sha256 = "875c188e9ff4dddca79a176ce87e10ca6c9255f91e8a99e5c03dda4bc134e746"
    url = "https://github.com/JuliaBinaryWrappers/Minuit2_jll.jl/releases/download/Minuit2-v6.34.2+0/Minuit2.v6.34.2.x86_64-w64-mingw32-cxx11.tar.gz"
