# Autogenerated wrapper script for Minuit2_jll for x86_64-apple-darwin
export libMinuit2, libMinuit2Math

JLLWrappers.@generate_wrapper_header("Minuit2")
JLLWrappers.@declare_library_product(libMinuit2, "@rpath/libMinuit2.dylib")
JLLWrappers.@declare_library_product(libMinuit2Math, "@rpath/libMinuit2Math.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libMinuit2,
        "lib/libMinuit2.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libMinuit2Math,
        "lib/libMinuit2Math.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
